<x-layout>
    <x-slot name="title">Revenue Report</x-slot>

    @php
        $reportConfig = config('reports.revenue');
        $companyConfig = config('reports.company');
        $printConfig = config('reports.print');
        $currency = $reportConfig['currency'] ?? '₱';
        $dateFormat = $reportConfig['date_format'] ?? 'F d, Y';
        $timeFormat = $reportConfig['time_format'] ?? 'h:i A';
    @endphp

    <!-- Print Header (only visible when printing) -->
    <div class="hidden print:block mb-8">
        <div class="text-center border-b-2 border-gray-800 pb-4 mb-4">
            @if($reportConfig['show_logo'] && $companyConfig['logo'])
                <img src="{{ asset($companyConfig['logo']) }}" alt="Logo" class="h-12 mx-auto mb-2">
            @endif
            <h1 class="text-2xl font-bold uppercase">{{ $reportConfig['title'] ?? 'Revenue Report' }}</h1>
            @if($reportConfig['show_company_info'])
                <p class="text-sm text-gray-600 mt-1">{{ $companyConfig['name'] }}</p>
                @if($companyConfig['address'])
                    <p class="text-xs text-gray-500">{{ $companyConfig['address'] }}</p>
                @endif
                @if($companyConfig['phone'] || $companyConfig['email'])
                    <p class="text-xs text-gray-500">
                        @if($companyConfig['phone'])Tel: {{ $companyConfig['phone'] }}@endif
                        @if($companyConfig['phone'] && $companyConfig['email']) | @endif
                        @if($companyConfig['email'])Email: {{ $companyConfig['email'] }}@endif
                    </p>
                @endif
            @endif
        </div>
        <div class="flex justify-between text-sm mb-4">
            <div>
                <p><strong>Report Period:</strong> {{ $allTime ? 'All Time' : $start->format($dateFormat) . ' - ' . $end->format($dateFormat) }}</p>
                <p><strong>Generated:</strong> {{ now()->format($dateFormat . ' ' . $timeFormat) }}</p>
                @if($reportConfig['show_report_id'])
                    <p><strong>Report ID:</strong> REV-{{ now()->format('YmdHis') }}</p>
                @endif
            </div>
            @if($reportConfig['show_generated_by'])
            <div class="text-right">
                <p><strong>Generated By:</strong> {{ Auth::guard('admin')->user()->fname }} {{ Auth::guard('admin')->user()->lname }}</p>
            </div>
            @endif
        </div>
    </div>

    <div class="max-w-7xl mx-auto space-y-6">
        <!-- Hero Header -->
        <div class="relative bg-gradient-to-br from-wash via-wash-dark to-gray-900 rounded-2xl p-12 overflow-hidden">
            <!-- Decorative Background -->
            <div class="absolute inset-0 opacity-10">
                <div class="absolute top-0 right-0 w-64 h-64 bg-white rounded-full -translate-y-1/2 translate-x-1/2"></div>
                <div class="absolute bottom-0 left-0 w-48 h-48 bg-white rounded-full translate-y-1/2 -translate-x-1/2"></div>
            </div>
            
            <!-- Content -->
            <div class="relative flex items-center justify-between">
                <div>
                    <h1 class="text-5xl font-black text-white mb-3">Revenue Report</h1>
                    <p class="text-xl text-white/80">{{ $allTime ? 'All Time Data' : $start->format('M d, Y') . ' - ' . $end->format('M d, Y') }}</p>
                </div>
                <div class="flex gap-3">
                    <a href="{{ route('admin.revenue.export.csv', request()->all()) }}" class="inline-flex items-center px-4 py-2 bg-white/10 hover:bg-white/20 backdrop-blur text-white font-bold rounded-xl transition-colors text-sm">
                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                        CSV
                    </a>
                    <a href="{{ route('admin.revenue.export', request()->all()) }}" class="inline-flex items-center px-4 py-2 bg-white hover:bg-white/90 text-wash font-bold rounded-xl transition-all hover:scale-105 hover:shadow-xl text-sm">
                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                        </svg>
                        Export
                    </a>
                </div>
            </div>
        </div>

        <!-- Filters -->
        @php
            $isCustom = request('custom') == '1' || (request('start_date') && request('end_date') && !in_array($period, ['today', 'week', 'month', 'year']));
            $currentPeriod = $allTime ? 'all_time' : ($isCustom ? 'custom' : $period);
        @endphp
        <div class="bg-white rounded-2xl border-2 border-gray-200 p-6">
            <form action="{{ route('admin.revenue.index') }}" method="GET" class="space-y-4">
                <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3">
                    <button type="submit" name="period" value="today" class="px-4 py-2 rounded-xl border-2 {{ $currentPeriod === 'today' ? 'bg-info border-info text-white' : 'bg-info/5 border-info/20 text-gray-900 hover:bg-info hover:border-info hover:text-white' }} font-bold text-sm transition-all">
                        Today
                    </button>
                    <button type="submit" name="period" value="week" class="px-4 py-2 rounded-xl border-2 {{ $currentPeriod === 'week' ? 'bg-success border-success text-white' : 'bg-success/5 border-success/20 text-gray-900 hover:bg-success hover:border-success hover:text-white' }} font-bold text-sm transition-all">
                        This Week
                    </button>
                    <button type="submit" name="period" value="month" class="px-4 py-2 rounded-xl border-2 {{ $currentPeriod === 'month' ? 'bg-warning border-warning text-white' : 'bg-warning/5 border-warning/20 text-gray-900 hover:bg-warning hover:border-warning hover:text-white' }} font-bold text-sm transition-all">
                        This Month
                    </button>
                    <button type="submit" name="period" value="year" class="px-4 py-2 rounded-xl border-2 {{ $currentPeriod === 'year' ? 'bg-purple-600 border-purple-600 text-white' : 'bg-purple-600/5 border-purple-600/20 text-gray-900 hover:bg-purple-600 hover:border-purple-600 hover:text-white' }} font-bold text-sm transition-all">
                        This Year
                    </button>
                    <button type="submit" name="all_time" value="true" class="px-4 py-2 rounded-xl border-2 {{ $currentPeriod === 'all_time' ? 'bg-wash border-wash text-white' : 'bg-wash/5 border-wash/20 text-gray-900 hover:bg-wash hover:border-wash hover:text-white' }} font-bold text-sm transition-all">
                        All Time
                    </button>
                    <button type="button" onclick="document.getElementById('customDateRange').classList.toggle('hidden')" class="px-4 py-2 rounded-xl border-2 {{ $currentPeriod === 'custom' ? 'bg-error border-error text-white' : 'bg-error/5 border-error/20 text-gray-900 hover:bg-error hover:border-error hover:text-white' }} font-bold text-sm transition-all">
                        Custom
                    </button>
                </div>
                
                <div id="customDateRange" class="{{ $currentPeriod === 'custom' ? '' : 'hidden' }} grid grid-cols-1 md:grid-cols-3 gap-4 pt-4 border-t-2 border-gray-200">
                    <div class="form-group">
                        <label class="form-label">Start Date</label>
                        <input type="date" name="start_date" value="{{ request('start_date') }}" class="form-input">
                    </div>
                    <div class="form-group">
                        <label class="form-label">End Date</label>
                        <input type="date" name="end_date" value="{{ request('end_date') }}" class="form-input">
                    </div>
                    <div class="flex items-end gap-2">
                        <button type="submit" name="custom" value="1" class="btn btn-primary flex-1">
                            Apply
                        </button>
                        @if(request()->hasAny(['period', 'start_date', 'end_date', 'all_time', 'custom']))
                        <a href="{{ route('admin.revenue.index') }}" class="btn btn-secondary">
                            Clear
                        </a>
                        @endif
                    </div>
                </div>
            </form>
        </div>

        <!-- Stat Cards -->
        <div class="grid grid-cols-2 md:grid-cols-3 gap-4 print:grid-cols-3 print:gap-2">
            <!-- Total Revenue -->
            <div class="group relative bg-white rounded-2xl p-6 border-2 border-gray-200 hover:border-success transition-all overflow-hidden print:p-3">
                <div class="absolute top-0 right-0 w-24 h-24 bg-success/5 rounded-full -translate-y-1/2 translate-x-1/2 group-hover:scale-150 transition-transform"></div>
                <div class="relative">
                    <div class="w-12 h-12 bg-success/10 rounded-xl flex items-center justify-center mb-3">
                        <svg class="w-6 h-6 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </div>
                    <p class="text-xs text-gray-600 font-bold uppercase mb-1 print:text-xs">Total Revenue</p>
                    <p class="text-3xl font-black text-gray-900 print:text-xl">{{ $currency }}{{ number_format($totalRevenue, $reportConfig['decimal_places'] ?? 2) }}</p>
                </div>
            </div>

            <!-- Total Transactions -->
            <div class="group relative bg-white rounded-2xl p-6 border-2 border-gray-200 hover:border-wash transition-all overflow-hidden print:p-3">
                <div class="absolute top-0 right-0 w-24 h-24 bg-wash/5 rounded-full -translate-y-1/2 translate-x-1/2 group-hover:scale-150 transition-transform"></div>
                <div class="relative">
                    <div class="w-12 h-12 bg-wash/10 rounded-xl flex items-center justify-center mb-3">
                        <svg class="w-6 h-6 text-wash" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                        </svg>
                    </div>
                    <p class="text-xs text-gray-600 font-bold uppercase mb-1 print:text-xs">Total Transactions</p>
                    <p class="text-3xl font-black text-gray-900 print:text-xl">{{ number_format($totalTransactions) }}</p>
                </div>
            </div>

            <!-- Average Order -->
            <div class="group relative bg-white rounded-2xl p-6 border-2 border-gray-200 hover:border-info transition-all overflow-hidden print:p-3">
                <div class="absolute top-0 right-0 w-24 h-24 bg-info/5 rounded-full -translate-y-1/2 translate-x-1/2 group-hover:scale-150 transition-transform"></div>
                <div class="relative">
                    <div class="w-12 h-12 bg-info/10 rounded-xl flex items-center justify-center mb-3">
                        <svg class="w-6 h-6 text-info" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                        </svg>
                    </div>
                    <p class="text-xs text-gray-600 font-bold uppercase mb-1 print:text-xs">Average Order</p>
                    <p class="text-3xl font-black text-gray-900 print:text-xl">{{ $currency }}{{ number_format($averageOrder, $reportConfig['decimal_places'] ?? 2) }}</p>
                </div>
            </div>
        </div>

        <!-- Revenue by Service -->
        <div class="card p-6 print:p-4">
            <h2 class="text-xl font-semibold text-gray-900 mb-4 print:text-base print:mb-2">Revenue by Service Type</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 print:grid-cols-3 print:gap-2">
                @forelse($revenueByService as $service => $data)
                    <div class="border rounded-lg p-4 print:p-2 print:rounded-none">
                        <p class="text-sm text-gray-600 print:text-xs">{{ ucfirst(str_replace('_', ' ', $service)) }}</p>
                        <p class="text-2xl font-bold text-gray-900 mt-1 print:text-base print:mt-0">{{ $currency }}{{ number_format($data['revenue'], $reportConfig['decimal_places'] ?? 2) }}</p>
                        <p class="text-xs text-gray-500 mt-1 print:mt-0">{{ $data['count'] }} booking(s)</p>
                    </div>
                @empty
                    <p class="text-gray-500 col-span-3">No revenue data available</p>
                @endforelse
            </div>
        </div>

        <!-- Transactions Table -->
        <div class="card print:border-0">
            <div class="p-6 border-b print:p-2 print:border-b-2 print:border-gray-800">
                <h2 class="text-xl font-semibold text-gray-900 print:text-base">Transaction Details</h2>
                <p class="text-sm text-gray-500 print:text-xs">{{ $transactions->count() }} transaction(s) found</p>
            </div>
            <div class="overflow-x-auto print:overflow-visible">
                <table class="w-full print:text-xs">
                    <thead class="bg-gray-50 print:bg-gray-200">
                        <tr>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Date</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">ID</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Customer</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Service</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Status</th>
                            <th class="px-6 py-3 text-right text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Amount</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y print:divide-gray-300">
                        @forelse($transactions as $transaction)
                            <tr class="hover:bg-gray-50 print:hover:bg-transparent">
                                <td class="px-6 py-4 text-sm print:px-2 print:py-1">{{ $transaction->created_at->format('M d, Y') }}</td>
                                <td class="px-6 py-4 text-sm font-medium print:px-2 print:py-1">#{{ $transaction->id }}</td>
                                <td class="px-6 py-4 text-sm print:px-2 print:py-1">{{ $transaction->user ? $transaction->user->fname . ' ' . $transaction->user->lname : 'N/A' }}</td>
                                <td class="px-6 py-4 text-sm print:px-2 print:py-1">{{ ucfirst(str_replace('_', ' ', $transaction->item_type)) }}</td>
                                <td class="px-6 py-4 print:px-2 print:py-1">
                                    <span class="badge badge-{{ $transaction->status === 'completed' ? 'success' : 'primary' }} print:border print:border-gray-400 print:bg-transparent print:text-gray-800">
                                        {{ ucfirst($transaction->status) }}
                                    </span>
                                </td>
                                <td class="px-6 py-4 text-sm font-semibold text-right print:px-2 print:py-1">{{ $currency }}{{ number_format($transaction->total_price, $reportConfig['decimal_places'] ?? 2) }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6" class="px-6 py-12 text-center text-gray-500 print:py-4">No transactions found for this period</td>
                            </tr>
                        @endforelse
                    </tbody>
                    @if($transactions->count() > 0)
                        <tfoot class="bg-gray-50 font-semibold print:bg-gray-200">
                            <tr>
                                <td colspan="5" class="px-6 py-4 text-right print:px-2 print:py-2">Total Revenue:</td>
                                <td class="px-6 py-4 text-right print:px-2 print:py-2">{{ $currency }}{{ number_format($totalRevenue, $reportConfig['decimal_places'] ?? 2) }}</td>
                            </tr>
                        </tfoot>
                    @endif
                </table>
            </div>
        </div>
    </div>

    <!-- Print Summary (only visible when printing) -->
    <div class="hidden print:block mt-8 pt-4 border-t-2 border-gray-800">
        <div class="text-center text-xs text-gray-500">
            <p>{{ $reportConfig['footer_text'] ?? 'This is a computer-generated report. No signature required.' }}</p>
            <p>{{ $companyConfig['name'] }} | Generated: {{ now()->format($dateFormat . ' ' . $timeFormat) }}</p>
        </div>
    </div>

    @push('styles')
    <style>
        @media print {
            /* Reset and base styles */
            * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
            body { background: white !important; font-size: 12px; line-height: 1.4; }
            
            /* Hide non-print elements */
            .sidebar, .navbar, nav, .print\:hidden, button, .btn { display: none !important; }
            
            /* Layout adjustments */
            main { margin: 0 !important; padding: 0 !important; max-width: 100% !important; }
            .space-y-6 > * + * { margin-top: 1rem; }
            
            /* Card styling for print */
            .card { 
                box-shadow: none !important; 
                border: 1px solid #000 !important; 
                border-radius: 0 !important;
                page-break-inside: avoid;
                margin-bottom: 1rem;
            }
            
            /* Stats grid */
            .grid { display: flex !important; flex-wrap: wrap; gap: 0.5rem; }
            .grid > div { flex: 1; min-width: 150px; border: 1px solid #000 !important; padding: 0.75rem !important; }
            
            /* Table styling */
            table { width: 100%; border-collapse: collapse; font-size: 11px; }
            th, td { border: 1px solid #000 !important; padding: 6px 8px !important; text-align: left; }
            th { background: #f3f4f6 !important; font-weight: bold; }
            tbody tr:nth-child(even) { background: #f9fafb !important; }
            tfoot { background: #e5e7eb !important; font-weight: bold; }
            
            /* Badge styling for print */
            .badge { 
                border: 1px solid #000 !important; 
                padding: 2px 6px !important; 
                font-size: 10px !important;
                background: transparent !important;
                color: #000 !important;
            }
            
            /* Typography */
            h1 { font-size: 18px !important; }
            h2 { font-size: 14px !important; margin-bottom: 0.5rem !important; }
            .text-3xl { font-size: 20px !important; }
            .text-2xl { font-size: 16px !important; }
            .text-xl { font-size: 14px !important; }
            
            /* Colors for print */
            .text-success, .text-green-600 { color: #000 !important; }
            .text-primary, .text-blue-600 { color: #000 !important; }
            .text-gray-900 { color: #000 !important; }
            .text-gray-600, .text-gray-500 { color: #4b5563 !important; }
            
            /* Page settings */
            @page { 
                size: {{ $printConfig['page_size'] ?? 'A4' }} {{ $printConfig['orientation'] ?? 'portrait' }}; 
                margin: {{ $printConfig['margin_top'] ?? '1.5cm' }} {{ $printConfig['margin_right'] ?? '1.5cm' }} {{ $printConfig['margin_bottom'] ?? '1.5cm' }} {{ $printConfig['margin_left'] ?? '1.5cm' }}; 
            }
            
            /* Show print-only elements */
            .print\:block { display: block !important; }
            
            /* Prevent page breaks inside important elements */
            .card, tr { page-break-inside: avoid; }
        }
    </style>
    @endpush
</x-layout>
