<x-layout>
    <x-slot name="title">Revenue Report</x-slot>

    @php
        $reportConfig = config('reports.revenue');
        $companyConfig = config('reports.company');
        $printConfig = config('reports.print');
        $currency = $reportConfig['currency'] ?? '₱';
        $dateFormat = $reportConfig['date_format'] ?? 'F d, Y';
        $timeFormat = $reportConfig['time_format'] ?? 'h:i A';
    @endphp

    <!-- Print Header (only visible when printing) -->
    <div class="hidden print:block mb-8">
        <div class="text-center border-b-2 border-gray-800 pb-4 mb-4">
            @if($reportConfig['show_logo'] && $companyConfig['logo'])
                <img src="{{ asset($companyConfig['logo']) }}" alt="Logo" class="h-12 mx-auto mb-2">
            @endif
            <h1 class="text-2xl font-bold uppercase">{{ $reportConfig['title'] ?? 'Revenue Report' }}</h1>
            @if($reportConfig['show_company_info'])
                <p class="text-sm text-gray-600 mt-1">{{ $companyConfig['name'] }}</p>
                @if($companyConfig['address'])
                    <p class="text-xs text-gray-500">{{ $companyConfig['address'] }}</p>
                @endif
                @if($companyConfig['phone'] || $companyConfig['email'])
                    <p class="text-xs text-gray-500">
                        @if($companyConfig['phone'])Tel: {{ $companyConfig['phone'] }}@endif
                        @if($companyConfig['phone'] && $companyConfig['email']) | @endif
                        @if($companyConfig['email'])Email: {{ $companyConfig['email'] }}@endif
                    </p>
                @endif
            @endif
        </div>
        <div class="flex justify-between text-sm mb-4">
            <div>
                <p><strong>Report Period:</strong> {{ $allTime ? 'All Time' : $start->format($dateFormat) . ' - ' . $end->format($dateFormat) }}</p>
                <p><strong>Generated:</strong> {{ now()->format($dateFormat . ' ' . $timeFormat) }}</p>
                @if($reportConfig['show_report_id'])
                    <p><strong>Report ID:</strong> REV-{{ now()->format('YmdHis') }}</p>
                @endif
            </div>
            @if($reportConfig['show_generated_by'])
            <div class="text-right">
                <p><strong>Generated By:</strong> {{ Auth::guard('admin')->user()->fname }} {{ Auth::guard('admin')->user()->lname }}</p>
            </div>
            @endif
        </div>
    </div>

    <div class="space-y-6">
        <!-- Header -->
        <div class="card p-6 print:hidden">
            <div class="flex justify-between items-start">
                <div>
                    <h1 class="text-3xl font-bold text-gray-900">Revenue Report</h1>
                    <p class="text-gray-600 mt-1">{{ $allTime ? 'All Time Data' : $start->format('M d, Y') . ' - ' . $end->format('M d, Y') }}</p>
                </div>
                <div class="flex gap-2 print:hidden">
                    <a href="{{ route('admin.revenue.export.csv', request()->all()) }}" class="btn btn-secondary">
                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                        CSV
                    </a>
                    <a href="{{ route('admin.revenue.export', request()->all()) }}" class="btn btn-primary">
                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                        </svg>
                        Export Report
                    </a>
                </div>
            </div>
        </div>

        <!-- Filters -->
        <x-modules.filter-panel
            :action="route('admin.revenue.index')"
            :quick-filters="[
                ['label' => 'Today', 'url' => route('admin.revenue.index', ['period' => 'today']), 'active' => $period === 'today' && !$allTime],
                ['label' => 'This Week', 'url' => route('admin.revenue.index', ['period' => 'week']), 'active' => $period === 'week' && !$allTime],
                ['label' => 'This Month', 'url' => route('admin.revenue.index', ['period' => 'month']), 'active' => $period === 'month' && !$allTime],
                ['label' => 'This Year', 'url' => route('admin.revenue.index', ['period' => 'year']), 'active' => $period === 'year' && !$allTime],
                ['label' => 'All Time', 'url' => route('admin.revenue.index', ['all_time' => 'true']), 'active' => $allTime],
            ]"
            :show-date-range="true"
            :start-date-value="request('start_date')"
            :end-date-value="request('end_date')"
            :clear-url="route('admin.revenue.index')"
            :show-clear="request()->hasAny(['period', 'start_date', 'end_date', 'all_time'])"
            submit-text="Apply"
        >
            <x-slot name="fields">
                <div class="form-group">
                    <label class="form-label">Period</label>
                    <select name="period" class="form-select" {{ $allTime ? 'disabled' : '' }} onchange="this.form.submit()">
                        <option value="today" {{ $period === 'today' ? 'selected' : '' }}>Today</option>
                        <option value="week" {{ $period === 'week' ? 'selected' : '' }}>This Week</option>
                        <option value="month" {{ $period === 'month' ? 'selected' : '' }}>This Month</option>
                        <option value="year" {{ $period === 'year' ? 'selected' : '' }}>This Year</option>
                        <option value="custom" {{ $period === 'custom' ? 'selected' : '' }}>Custom Range</option>
                    </select>
                </div>
            </x-slot>
            <x-slot name="after">
                <div class="form-group mt-4 pt-4 border-t border-gray-200">
                    <label class="flex items-center gap-2 cursor-pointer">
                        <input type="checkbox" name="all_time" value="true" class="form-checkbox h-5 w-5 text-primary-600 rounded" {{ $allTime ? 'checked' : '' }} onchange="this.form.submit()">
                        <span class="text-sm font-medium text-gray-700">Show All Data</span>
                    </label>
                </div>
            </x-slot>
        </x-modules.filter-panel>

        <!-- Stats -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 print:grid-cols-3 print:gap-2">
            <div class="card p-6 print:p-3">
                <p class="text-sm text-gray-600 print:text-xs">Total Revenue</p>
                <p class="text-3xl font-bold text-success mt-2 print:text-xl print:mt-1">{{ $currency }}{{ number_format($totalRevenue, $reportConfig['decimal_places'] ?? 2) }}</p>
            </div>
            <div class="card p-6 print:p-3">
                <p class="text-sm text-gray-600 print:text-xs">Total Transactions</p>
                <p class="text-3xl font-bold text-primary mt-2 print:text-xl print:mt-1">{{ number_format($totalTransactions) }}</p>
            </div>
            <div class="card p-6 print:p-3">
                <p class="text-sm text-gray-600 print:text-xs">Average Order</p>
                <p class="text-3xl font-bold text-gray-900 mt-2 print:text-xl print:mt-1">{{ $currency }}{{ number_format($averageOrder, $reportConfig['decimal_places'] ?? 2) }}</p>
            </div>
        </div>

        <!-- Revenue by Service -->
        <div class="card p-6 print:p-4">
            <h2 class="text-xl font-semibold text-gray-900 mb-4 print:text-base print:mb-2">Revenue by Service Type</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 print:grid-cols-3 print:gap-2">
                @forelse($revenueByService as $service => $data)
                    <div class="border rounded-lg p-4 print:p-2 print:rounded-none">
                        <p class="text-sm text-gray-600 print:text-xs">{{ ucfirst(str_replace('_', ' ', $service)) }}</p>
                        <p class="text-2xl font-bold text-gray-900 mt-1 print:text-base print:mt-0">{{ $currency }}{{ number_format($data['revenue'], $reportConfig['decimal_places'] ?? 2) }}</p>
                        <p class="text-xs text-gray-500 mt-1 print:mt-0">{{ $data['count'] }} booking(s)</p>
                    </div>
                @empty
                    <p class="text-gray-500 col-span-3">No revenue data available</p>
                @endforelse
            </div>
        </div>

        <!-- Transactions Table -->
        <div class="card print:border-0">
            <div class="p-6 border-b print:p-2 print:border-b-2 print:border-gray-800">
                <h2 class="text-xl font-semibold text-gray-900 print:text-base">Transaction Details</h2>
                <p class="text-sm text-gray-500 print:text-xs">{{ $transactions->count() }} transaction(s) found</p>
            </div>
            <div class="overflow-x-auto print:overflow-visible">
                <table class="w-full print:text-xs">
                    <thead class="bg-gray-50 print:bg-gray-200">
                        <tr>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Date</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">ID</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Customer</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Service</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Status</th>
                            <th class="px-6 py-3 text-right text-xs font-semibold text-gray-600 uppercase print:px-2 print:py-1">Amount</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y print:divide-gray-300">
                        @forelse($transactions as $transaction)
                            <tr class="hover:bg-gray-50 print:hover:bg-transparent">
                                <td class="px-6 py-4 text-sm print:px-2 print:py-1">{{ $transaction->created_at->format('M d, Y') }}</td>
                                <td class="px-6 py-4 text-sm font-medium print:px-2 print:py-1">#{{ $transaction->id }}</td>
                                <td class="px-6 py-4 text-sm print:px-2 print:py-1">{{ $transaction->user ? $transaction->user->fname . ' ' . $transaction->user->lname : 'N/A' }}</td>
                                <td class="px-6 py-4 text-sm print:px-2 print:py-1">{{ ucfirst(str_replace('_', ' ', $transaction->item_type)) }}</td>
                                <td class="px-6 py-4 print:px-2 print:py-1">
                                    <span class="badge badge-{{ $transaction->status === 'completed' ? 'success' : 'primary' }} print:border print:border-gray-400 print:bg-transparent print:text-gray-800">
                                        {{ ucfirst($transaction->status) }}
                                    </span>
                                </td>
                                <td class="px-6 py-4 text-sm font-semibold text-right print:px-2 print:py-1">{{ $currency }}{{ number_format($transaction->total_price, $reportConfig['decimal_places'] ?? 2) }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6" class="px-6 py-12 text-center text-gray-500 print:py-4">No transactions found for this period</td>
                            </tr>
                        @endforelse
                    </tbody>
                    @if($transactions->count() > 0)
                        <tfoot class="bg-gray-50 font-semibold print:bg-gray-200">
                            <tr>
                                <td colspan="5" class="px-6 py-4 text-right print:px-2 print:py-2">Total Revenue:</td>
                                <td class="px-6 py-4 text-right print:px-2 print:py-2">{{ $currency }}{{ number_format($totalRevenue, $reportConfig['decimal_places'] ?? 2) }}</td>
                            </tr>
                        </tfoot>
                    @endif
                </table>
            </div>
        </div>
    </div>

    <!-- Print Summary (only visible when printing) -->
    <div class="hidden print:block mt-8 pt-4 border-t-2 border-gray-800">
        <div class="text-center text-xs text-gray-500">
            <p>{{ $reportConfig['footer_text'] ?? 'This is a computer-generated report. No signature required.' }}</p>
            <p>{{ $companyConfig['name'] }} | Generated: {{ now()->format($dateFormat . ' ' . $timeFormat) }}</p>
        </div>
    </div>

    @push('styles')
    <style>
        @media print {
            /* Reset and base styles */
            * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
            body { background: white !important; font-size: 12px; line-height: 1.4; }
            
            /* Hide non-print elements */
            .sidebar, .navbar, nav, .print\:hidden, button, .btn { display: none !important; }
            
            /* Layout adjustments */
            main { margin: 0 !important; padding: 0 !important; max-width: 100% !important; }
            .space-y-6 > * + * { margin-top: 1rem; }
            
            /* Card styling for print */
            .card { 
                box-shadow: none !important; 
                border: 1px solid #000 !important; 
                border-radius: 0 !important;
                page-break-inside: avoid;
                margin-bottom: 1rem;
            }
            
            /* Stats grid */
            .grid { display: flex !important; flex-wrap: wrap; gap: 0.5rem; }
            .grid > div { flex: 1; min-width: 150px; border: 1px solid #000 !important; padding: 0.75rem !important; }
            
            /* Table styling */
            table { width: 100%; border-collapse: collapse; font-size: 11px; }
            th, td { border: 1px solid #000 !important; padding: 6px 8px !important; text-align: left; }
            th { background: #f3f4f6 !important; font-weight: bold; }
            tbody tr:nth-child(even) { background: #f9fafb !important; }
            tfoot { background: #e5e7eb !important; font-weight: bold; }
            
            /* Badge styling for print */
            .badge { 
                border: 1px solid #000 !important; 
                padding: 2px 6px !important; 
                font-size: 10px !important;
                background: transparent !important;
                color: #000 !important;
            }
            
            /* Typography */
            h1 { font-size: 18px !important; }
            h2 { font-size: 14px !important; margin-bottom: 0.5rem !important; }
            .text-3xl { font-size: 20px !important; }
            .text-2xl { font-size: 16px !important; }
            .text-xl { font-size: 14px !important; }
            
            /* Colors for print */
            .text-success, .text-green-600 { color: #000 !important; }
            .text-primary, .text-blue-600 { color: #000 !important; }
            .text-gray-900 { color: #000 !important; }
            .text-gray-600, .text-gray-500 { color: #4b5563 !important; }
            
            /* Page settings */
            @page { 
                size: {{ $printConfig['page_size'] ?? 'A4' }} {{ $printConfig['orientation'] ?? 'portrait' }}; 
                margin: {{ $printConfig['margin_top'] ?? '1.5cm' }} {{ $printConfig['margin_right'] ?? '1.5cm' }} {{ $printConfig['margin_bottom'] ?? '1.5cm' }} {{ $printConfig['margin_left'] ?? '1.5cm' }}; 
            }
            
            /* Show print-only elements */
            .print\:block { display: block !important; }
            
            /* Prevent page breaks inside important elements */
            .card, tr { page-break-inside: avoid; }
        }
    </style>
    @endpush
</x-layout>
